#!/bin/bash
mode: "inference"
use_cuda: 1 # 1 for True, 0 for False
num_gpu: 1
sampling_rate: 16000
network: "MossFormer2_SS_16K" ##network type
checkpoint_dir: "checkpoints/MossFormer2_SS_16K"
input_path: "data/wsj0_2mix_16k_fullpath.lst" # an input dir or input scp file
output_dir: "outputs/MossFormer2_SS_16K_wsj0_2mix" ## output dir to store processed audio

# decode parameters
one_time_decode_length: 5 #maximum segment length for one-pass decoding (seconds). longer audio (>5s) will use segmented decoding
decode_window: 5 #one-pass decoding length

num_spks: 2
encoder_kernel_size: 16
encoder_embedding_dim: 512
mossformer_sequence_dim: 512
num_mossformer_layer: 24
